{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{job=\"node_exporter\", mode=\"user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_network_transmit_packets_total{job=\"node_exporter\", device=\"eth0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP REQUESTS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_http_requests_total{instance=\"lb1:9113\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nginx_http_requests_total{instance=\"lb2:9113\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VIP OWNER",
   "type": "timeseries",
   "description": "2-OWNER 1-BACKUP",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{job=\"keepalived\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BACKEND STATUS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "up{job=\"nginx\", instance=\"backend1:9113\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "up{job=\"nginx\", instance=\"backend2:9113\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}